#!/bin/sh -e
#===================================================================
# Ma_Sys.ma Mount Script 1.0.1, Copyright (c) 2013, 2020 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.
#===================================================================

ALLOWED_DIRECTORIES="/fs/e01/imp /home/linux-fan"

main() {
	if [ $# = 0 ]; then
		usage
		exit 1
	fi
	if [ "$1" = "dev" -a $# = 1 ]; then
		list_devices
		exit 0
	fi
	case "$1" in
		(--help)  usage; return;;
		(dev|iso) exec /usr/bin/sudo "$0" sub "$@";;
		(sub)     shift; run_sub "$@";;
		(*)       echo Unsupported option: $1. Try --help.; exit 1;;
	esac
}

usage() {
	head -n 6 "$0" | tail -n 5 | cut -c 2-
	cat <<EOF
USAGE $0 dev [-u] [DEVICE]
USAGE $0 iso IMAGE MOUNTPOINT

Modes
-----

dev  Mounts DEVICE e.g. sde1 somewhere below /media. -u umounts instead.
iso  Mounts IMAGE at MOUNTPOINT which must be below an allowed directory.

Allowed directories
-------------------

Allowed directories are separated by a space:
$ALLOWED_DIRECTORIES
EOF
}

list_devices() {
	echo These devices may be mounted
	echo ----------------------------
	echo
	for i in /dev/sd??; do
		printf "%-10s" "$(basename "$i")"
	done
	echo
	echo
	echo These device mountpoints may be umounted
	echo ----------------------------------------
	echo
	while read -r line; do
		mnt="$(echo "$line" | cut -d " " -f 2)"
		if echo "$mnt" | grep -q -E '^/media/sd[b-z][1-9]$'; then
			printf "%-10s" "$(basename "$mnt")"
		fi
	done < /proc/mounts
	echo
}

run_sub() {
	case "$1" in
		(dev) shift; mount_dev "$@";;
		(iso) shift; mount_iso "$@";;
	esac
}

mount_dev() {
	umount=
	if [ "$1" = "-u" ]; then
		umount=true
		shift
	else 
		umount=false
	fi
	if ! echo "$1" | grep -q -E '^sd[b-z][1-9]$'; then
		echo Invalid device name $1.
		exit 1
	fi
	if [ $umount = true ]; then
		umount "/media/$1" && rmdir "/media/$1"
	else
		if ! [ -d "/media/$1" ]; then
			mkdir "/media/$1"
			chmod 777 "/media/$1"
		elif [ $(ls "/media/$1" | wc -l) != 0 ]; then
			echo Directory not empty: /media/$1. Already mounted?
			exit 1
		fi
		exec mount -o "rw,uid=1000,gid=1000" "/dev/$1" "/media/$1"
	fi
}

mount_iso() {
	img="$1"
	mountpoint="$(realpath "$2")"
	# Check if mountpoint is below any of the safe directories. I hope this
	# test is safe enough. Cf. http://unix.stackexchange.com/questions/6435/
	# 		how-to-check-if-pwd-is-a-subdirectory-of-a-given-path
	valid=false
	for i in $ALLOWED_DIRECTORIES; do
		if [ "${mountpoint##$i}" != "$mountpoint" ]; then
			valid=true
			break
		fi
	done
	if [ "$valid" = "false" ]; then
		echo The given mountpoint $mountpoint is not below one of the \
							allowed directories.
		echo Check $0 --help.
		exit 1
	elif [ ! -f "$img" ]; then
		echo Image file $img does not exist.
		exit 1
	else
		exec mount -o loop,ro "$img" "$mountpoint"
	fi
}

main "$@"
